spring:
  application:
    name: api-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maindb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: root1234!
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    org:
      springframework:
        security: DEBUG